interface CoverageBadgeProps {
  /** Package name, e.g., "@layers/models" */
  package: string;
  /** Coverage percentage (0-100) */
  coverage?: number;
}

/**
 * Displays test coverage badge for a package.
 *
 * Coverage data is generated by CI and stored in public/coverage/[package].json
 *
 * @example
 * ```tsx
 * <CoverageBadge package="@layers/models" coverage={87} />
 * ```
 */
export function CoverageBadge({ package: pkg, coverage }: CoverageBadgeProps) {
  if (coverage === undefined) {
    return (
      <span className="inline-flex items-center px-2 py-1 rounded text-xs bg-muted text-muted-foreground">
        Coverage: N/A
      </span>
    );
  }

  const getColor = (pct: number) => {
    if (pct >= 80) return 'bg-green-100 text-green-800';
    if (pct >= 60) return 'bg-yellow-100 text-yellow-800';
    return 'bg-red-100 text-red-800';
  };

  return (
    <span
      className={`inline-flex items-center px-2 py-1 rounded text-xs font-medium ${getColor(coverage)}`}
    >
      Coverage: {coverage}%
    </span>
  );
}
